language: java
jdk: oraclejdk8
before_install: ./.travis.before_install.sh
script: ./.travis.script.sh

addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable

# Run on a dedicated Trusty VM to avoid random problems like "User limit of inotify watches reached"
sudo: required
dist: trusty

deploy:
  - provider: script
    script: ./.travis.deploy.sh
    skip_cleanup: true
    on:
      branch: master

# Cache requires a master build
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.m2
  - flow-tests/test-root-context/frontend/node
  - flow-tests/test-root-context/frontend/node_modules
  - flow-tests/test-root-context/frontend/bower_components
  - flow-tests/test-expense-manager-imperative/frontend/node
  - flow-tests/test-expense-manager-imperative/frontend/node_modules
  - flow-tests/test-expense-manager-imperative/frontend/bower_components
  - flow-tests/test-polymer2/driver
before_cache:
  # remove all build artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/flow
  - rm -rf $HOME/.m2/repository/com/vaadin/flow-*
after_failure: ./.travis.after_failure.sh
