language: java
jdk: oraclejdk8
before_install: ./.travis.before_install.sh
script: ./.travis.script.sh

# Run on a dedicated Trusty VM to avoid random problems like "User limit of inotify watches reached"
sudo: required
dist: trusty

# Cache requires a master build
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.m2
  - hummingbird-tests/test-root-context/frontend/node
  - hummingbird-tests/test-root-context/frontend/node_modules
  - hummingbird-tests/test-root-context/frontend/bower_components
  - hummingbird-tests/test-expense-manager-imperative/frontend/node
  - hummingbird-tests/test-expense-manager-imperative/frontend/node_modules
  - hummingbird-tests/test-expense-manager-imperative/frontend/bower_components
  - hummingbird-tests/hummingbird-tests/test-polymer2/driver
before_cache:
  # remove all build artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/hummingbird
  - rm -rf $HOME/.m2/repository/com/vaadin/hummingbird-*
after_failure: ./.travis.after_failure.sh

